name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
    tags:
      - "**"
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Gradle
      run: |
        ./gradlew build
    - name: Rename script jar
      run: |
        mv "./build/libs/Script Template-1.0.jar" ./${{ github.event.repository.name }}.jar
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}
        path: ./${{ github.event.repository.name }}.jar
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./${{ github.event.repository.name }}.jar

